image: gradle:jdk17-alpine

stages:
  - test
  - build

cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
    - cache/caches/
    - cache/notifications/
    - cache/wrapper/

test:
  stage: test
  script:
    - gradle --build-cache --gradle-user-home cache/ check

build:
  stage: build
  script:
    - gradle --gradle-user-home cache/ publish -x test